# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('resources/icons', 'resources/icons'),
        ('resources/sounds', 'resources/sounds'),
        ('resources/styles', 'resources/styles'),
    ],
    hiddenimports=[
        'PySide6.QtMultimedia',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'core',
        'core.di',
        'core.di.container',
        'core.app',
        'core.event_bus',
        'core.main_window',
        'core.navigation',
        'datebase',
        'datebase.db_manager',
        'datebase.db_queries',
        'datebase.repositories',
        'models',
        'modules',
        'modules.analytics',
        'modules.dashboard',
        'modules.flashcards',
        'modules.music',
        'modules.notes',
        'modules.search',
        'modules.sessions',
        'modules.settings',
        'modules.tasks',
        'modules.topics',
        'onboarding',
        'services',
        'utils',
        'widgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='HarmonyFlowNotes',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='resources/icons/app.ico',  # раскомментируйте, если есть .ico файл
)